### ISSUE TITLE
Application fails to launch throwing the following error

### ISSUE THREAD

**Issue by xayron** [MarloKessler/flutter-extended_shared_preferences#1]
```The plugin `extended_shared_preferences` doesn't have a main class defined in
C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\extended_shared_preferences-1.0.0\android\src\main\java\com\connapptivity\developer\sharedpreferences\SharedpreferencesPlugin.java or
C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\extended_shared_preferences-1.0.0\android\src\main\kotlin\com\connapptivity\developer\sharedpreferences\SharedpreferencesPlugin.kt. This is likely to due to an incorrect `androidPackage: com.connapptivity.developer.sharedpreferences` or `mainClass` entry in the       
plugin's pubspec.yaml
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of  this plugin and consider using a different plugin in the meanwhile.```

If this is an error on my side, I will remove this, but for time being, I'm submitting this as on isse. The application fails to buils throwing the following error. Please look into this asap.

**Comment by marlokessler** [comment]
This issue happened due to a wrong config in pubspec.yaml. I think it is solved and will close this thread, but feel free to reopen if the error still occurs. Feel also free to fork, solve errors and make a pull request, since this is free for everybody.

Best regards
Marlo

**Comment by nandakav** [comment]
Can you tell how this issue was fixed? Please tell the correct pubspec.yaml configuration. I have another issue opened for this.
