### ISSUE TITLE
pubspec.yaml has version 1.0.0.. Probably needs to be updated to 1.0.1 

### ISSUE THREAD

**Issue by nandakav** [MarloKessler/flutter-extended_shared_preferences#3]
Hey, I had filed issue2 earlier. There is a problem as the latest version is 1.0.0 in ur repository. The new changes need to be probably 1.0.1. I am not able to pull in the latest changes after pub get upgrade.

**Comment by marlokessler** [comment]
Thanks for evaluating this issue. I hope I solved it with the latest release, so please try it out and let me know, if it works! If it does, I will close this issue.

**Comment by nandakav** [comment]
Yes it is solved.
