### ISSUE TITLE
Extended shared preferences fails to load on restarting app

### ISSUE THREAD

**Issue by nandakav** [MarloKessler/flutter-extended_shared_preferences#4]
I am trying to use this plugin but I run into a problem.
The problem is that the plugin creates the filenam.xml correctly in the shared_prefs folder. 
However when I restart the app it does not read the shared preferences file and we get null.

**Comment by nandakav** [comment]
In the pubspec.yaml I have
extended_shared_preferences: ^1.0.2

All other plugins work correctly.
Using windows X.

Android studio 3.6.3

flutter doctor summary.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.1)
[!] Connected device

**Comment by nandakav** [comment]
I have confirmed that this particular version by @axel-op works.
 https://github.com/flutter/flutter/issues/14337#issuecomment-525947648

There is probably some bug in the android version.

**Comment by nandakav** [comment]
I have sent a pull request to fix the issue. 
There are 2 primary issues one is must fix. 
The second is desirable.

The pull request is for the main issue. 
The kotlin MethodCallHandlerSharedPreferences.kt file has PREFIX value set wrongly.
It should be set to empty string "" for compatibility with older Android builds. 

The second issue I see is that the SharedPreferences constructor returns without initializing the preference cache. 
This is because reload is an async call and we cant wait in the constructor. 
It is a good idea to introduce a getInstance() method which will do initialization before using the plugin. 

There is a workaround wherein one can call await reload(). If code need not be changed then we have to document this.
We can also introduce an init() API which internally calls reload() for posterity.

**Comment by marlokessler** [comment]
I merged your pull request to solve the error regarding the wrong prefix. Introducing a getInstance() method sounds good. Could you implement this method? Or what do you think is best?

**Comment by nandakav** [comment]
Yes getInstance() sounds good. 
I am not a kotlin developer. But I can implement if needed. 
It would be good if you can cut a release at the earliest with version 1.0.3.

**Comment by nandakav** [comment]
If it's not much effort for you, you could call reload() inside getInstance().

**Comment by nandakav** [comment]
I feel having a static getInstance() would not help our cause. We need to have separate instances of this class so that multiple pref files can be accessed.

So it is better to call an init() function instead of static getInstance()

**Comment by nandakav** [comment]
I have sent a pull request for init() call as per this discussion If you have a better idea you can try it out.

**Comment by marlokessler** [comment]
Hey @nandakav I agree with not having a static `getInstance()` class is better. Nevertheless, I think calling the method `init()` might cause confusion with the real initializer, that's why I will rename it to `loadPersistentStore()`. Thank you a lot for your work!

**Comment by marlokessler** [comment]
It works with me, could you test whether it works with you too? If it does, I will release it with version 1.0.3.

**Comment by nandakav** [comment]
Hey @MarloKessler there is one compilation issue with kotlin file in the PREFIX = ''. The equal to was missing in kotlin file. 
I have created a pull request for it.
After that change all else worked fine. The changes you have made are working fine. You can pull that change and cut a new version. Thanks for all the support.

**Comment by nandakav** [comment]
Please find the pull request.

**Comment by marlokessler** [comment]
Alright I merged it, hopefully it works now. Thank you!

**Comment by nandakav** [comment]
Everything is fine now. please increase the version and close the issue.

**Comment by marlokessler** [comment]
Alright, version 1.0.3 is out now!
